!-------------------------------------------------------
!
! Trap: calculate the thermal conductivity
!
! By Yanlei Wang,@THU,Mar 2013
! The input file '0vacf.data' is generated by vacf_fft.f90
! The output file is '3tc.data'
!-------------------------------------------------------
PROGRAM trap

!  use, intrinsic :: iso_c_binding
!  include 'fftw3.f03'
!  include 'mkl_vml.h'
  
!  IMPLICIT NONE
  INTEGER :: argc,i,j,k,l,tag
  INTEGER :: istep,jstep,nsteps,natoms,step_start,nlines
  INTEGER,PARAMETER :: MAXLINES = 1000000000
  DOUBLE PRECISION :: timestep,dt,sumcorr,pi,sum1
  DOUBLE PRECISION :: temp,T,lx,ly,V,scale1
  DOUBLE PRECISION :: kB,eV2J,A2m,ps2s,convert
  DOUBLE PRECISION :: f1(3),f2(3)
  DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: vacf,tc
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: time,tcall
  

  pi=3.1415926d0
  dt=0.001d0  !the timestep in inputdata
 
!----- 
  kB=1.3806504d-23
  eV2J=1.602d-19    
  A2m=1.0d-10      
  ps2s=1.0d-12      
  convert=eV2J*eV2J/ps2s/A2m
!--inint condiction
  T=298.d0
  lx=180.0d0
  ly=311.76920d0
  V=lx*ly*3.2d0
  scale1= convert*dt/kB/T/T/V

  scale1=1.0/3; ! for caculation of Diffusion 
  write(*, *) "Now Caculation of Diffusion ..."

!input file and output file
  OPEN (10, FILE='run.info', STATUS='OLD')
  read(10, *) natoms
  read(10, *) allstep
  read(10, *) ndump
  read(10 ,*) ions  ! 0 is cation, 1 is anion 
  nsteps=allstep/ndump !the total steps
  write(*, *)  "Total step = ", nsteps
  dt=ndump/(1.0E6) !!! unit ns



  OPEN (15,FILE='0vacf.data')
  OPEN (12,FILE='3tc.data',STATUS='UNKNOWN')
  
 !! nsteps = 2000001 
  msteps = nsteps/2 ! the integral steps 
 
!---------------------------------------------
! allocate data from dump file
!---------------------------------------------
  ! allocate data from dump file
  ALLOCATE(vacf(nsteps))
  ALLOCATE(time(nsteps))
  allocate(tc(nsteps))
  allocate(tcall(nsteps))

write(*,*) 1
!--------------------------------------------
! read data from dump file
!--------------------------------------------
!  REWIND(15)

  READ (15,*)
  READ (15,*)
!  READ (15,*)  
  DO i = 1, nsteps 
    READ (15,*) time(i),vacf(i)
  END DO
  CLOSE(15)
write(*,*) 3
!--------------------------------------------
! calculate the thermal conductivity
!--------------------------------------------


!do j=1,3
!  do i=1,nsteps
!    vacf(i,j) = vacf(i,j)/(nsteps+1-i)
!  end do
!end do

do j=1,1
   sum1=vacf(1)/2.d0
   tc(1)=sum1
   do i=2,msteps
     tc(i)=vacf(i)/2.d0+sum1   
     sum1=vacf(i)+sum1
   end do
   
   do i=1,msteps
     tc(i)=tc(i)*scale1
   end do
end do

! do i=1,msteps
!   tcall(i)=tc(i,1)+tc(i,2)+tc(i,3)
! end do

!--------------------------
!Export the results
!--------------------------------------------  
!  write (12,*) " Select first ", msteps, " for interation ..."
!  write (12,'(I8)')  nsteps
!  write (12,*) "time k11 k22 k33 k"
  DO i = 1, msteps
    WRITE(12,'(2F30.20)') i*dt,tc(i)*dt
  END DO
  CLOSE(12)
END program trap

